
export enum DrawingMode {
  SELECT = 'select',
  DRAW = 'draw',
  PENCIL = 'pencil',
  HAND = 'hand',
  STRAIGHT_LINE = 'straight_line',
  RECTANGLE = 'rectangle',
  CIRCLE = 'circle',
  TEXT = 'text',
  WALL = 'wall',
  ROOM = 'room',
  DOOR = 'door',
  WINDOW = 'window',
  MEASURE = 'measure',
  ERASER = 'eraser',
  PAN = 'pan',
  LINE = 'line',
  RECT = 'rect',
  ERASE = 'erase',
  ZOOM = 'zoom',
  SHAPE = 'shape',
  DIMENSION = 'dimension',
  STAIR = 'stair',
  COLUMN = 'column'
}
