
export enum DrawingMode {
  SELECT = 'SELECT',
  DRAW = 'DRAW',
  PENCIL = 'PENCIL',
  LINE = 'LINE',
  RECT = 'RECTANGLE',
  WALL = 'WALL',
  ROOM = 'ROOM',
  RECTANGLE = 'RECTANGLE',
  CIRCLE = 'CIRCLE',
  TEXT = 'TEXT',
  MEASURE = 'MEASURE',
  HAND = 'HAND',
  STRAIGHT_LINE = 'STRAIGHT_LINE',
  PAN = 'PAN',
  ZOOM = 'ZOOM',
  ERASER = 'ERASER',
  NONE = 'NONE'
}
