
/**
 * Grid rendering constants
 */

export const SMALL_GRID_COLOR = '#e0e0e0';
export const LARGE_GRID_COLOR = '#c0c0c0'; 
export const SMALL_GRID_WIDTH = 0.5;
export const LARGE_GRID_WIDTH = 1;
export const SMALL_GRID_SIZE = 10;
export const LARGE_GRID_SIZE = 50;

export const GRID_CONSTANTS = {
  DEFAULT_GRID_SIZE: 50,
  DEFAULT_GRID_COLOR: 'rgba(200, 200, 200, 0.2)',
  DEFAULT_GRID_OPACITY: 0.4,
  MAJOR_GRID_INTERVAL: 5,
  MAJOR_GRID_COLOR: 'rgba(180, 180, 180, 0.5)',
  MAJOR_GRID_OPACITY: 0.6,
  SMALL: {
    COLOR: SMALL_GRID_COLOR,
    WIDTH: SMALL_GRID_WIDTH,
    SIZE: SMALL_GRID_SIZE
  },
  LARGE: {
    COLOR: LARGE_GRID_COLOR,
    WIDTH: LARGE_GRID_WIDTH,
    SIZE: LARGE_GRID_SIZE
  }
};
