
import {
  AiOutlineSelect,
  AiOutlineEdit,
  AiOutlineDelete,
  AiOutlinePlusCircle,
  AiOutlineSearch,
  AiOutlineLogin,
  AiOutlineSwapRight,
  AiOutlineEye,
  AiOutlineSend,
  AiOutlineAppstore,
  AiOutlineHome,
  AiOutlineReload,
  AiOutlineLoading,
  AiOutlineSafety,
  AiOutlineWarning,
  AiOutlineCheckCircle,
  AiOutlineCloseCircle,
  AiOutlineKey,
  AiOutlineClockCircle,
  AiOutlineUpSquare, // Changed from AiOutlineSquare
  AiOutlineHolder,
  AiOutlineUpload,
  AiOutlineDownload,
  AiOutlineUndo,
  AiOutlineRedo,
  AiOutlineZoomIn,
  AiOutlineZoomOut,
  AiOutlineSync,
  AiOutlineTable,
  AiOutlineAlert, // Changed from AiOutlinePalette
  AiOutlinePlus,
  AiOutlineMinus,
  AiOutlineBgColors,
  AiOutlineSave,
  AiOutlineEdit as AiOutlinePencil
} from 'react-icons/ai';

export const Icons = {
  select: AiOutlineSelect,
  edit: AiOutlineEdit,
  delete: AiOutlineDelete,
  plus: AiOutlinePlus,
  plusCircle: AiOutlinePlusCircle,
  search: AiOutlineSearch,
  login: AiOutlineLogin,
  arrowRight: AiOutlineSwapRight,
  eye: AiOutlineEye,
  send: AiOutlineSend,
  grid: AiOutlineTable,
  home: AiOutlineHome,
  reload: AiOutlineReload,
  loading: AiOutlineLoading,
  shield: AiOutlineSafety,
  warning: AiOutlineWarning,
  check: AiOutlineCheckCircle,
  close: AiOutlineCloseCircle,
  key: AiOutlineKey,
  clock: AiOutlineClockCircle,
  square: AiOutlineUpSquare, // Changed from AiOutlineSquare
  holder: AiOutlineHolder,
  upload: AiOutlineUpload,
  download: AiOutlineDownload,
  undo: AiOutlineUndo,
  redo: AiOutlineRedo,
  zoomIn: AiOutlineZoomIn,
  zoomOut: AiOutlineZoomOut,
  sync: AiOutlineSync,
  palette: AiOutlineAlert, // Changed from AiOutlinePalette
  minus: AiOutlineMinus,
  paintBucket: AiOutlineBgColors,
  save: AiOutlineSave,
  pencil: AiOutlinePencil
};

export type IconName = keyof typeof Icons;
