
/**
 * Geometry constants for calculations and operations
 * Re-exports from central numerics module
 * @module constants
 */

// Re-export from central constants module
import {
  GRID_SPACING,
  CLOSE_POINT_THRESHOLD,
  SHAPE_CLOSE_THRESHOLD,
  FLOATING_POINT_TOLERANCE,
  MIN_LINE_LENGTH,
  MIN_SHAPE_AREA,
  ANGLE_SNAP_THRESHOLD,
  LARGE_GRID_LINE_WIDTH,
  SMALL_GRID_LINE_WIDTH,
  AREA_PRECISION,
  DISTANCE_PRECISION
} from '@/constants/numerics';

export {
  GRID_SPACING,
  CLOSE_POINT_THRESHOLD,
  SHAPE_CLOSE_THRESHOLD,
  FLOATING_POINT_TOLERANCE,
  MIN_LINE_LENGTH,
  MIN_SHAPE_AREA,
  ANGLE_SNAP_THRESHOLD,
  LARGE_GRID_LINE_WIDTH,
  SMALL_GRID_LINE_WIDTH,
  AREA_PRECISION,
  DISTANCE_PRECISION
};
