
import React from 'react';
import {
  AiOutlineSearch,
  AiOutlinePlus,
  AiOutlineMinus,
  AiOutlineEdit as AiOutlinePencil,
  AiOutlineSelect as AiOutlineMousePointer,
  AiOutlineLine as AiOutlinePenLine,
  AiOutlineDelete as AiOutlineEraser,
  AiOutlineAppstore as AiOutlineGrid,
  AiOutlineHome,
  AiOutlineSquare,
  AiOutlineHand,
  AiOutlineEye,
  AiOutlineSend,
  AiOutlinePlusCircle,
  AiOutlineLogin as AiOutlineLogIn,
  AiOutlineSwapRight as AiOutlineArrowRightLeft,
  AiOutlineSafety as AiOutlineShield,
  AiOutlineLoading as AiOutlineLoader,
  AiOutlineWarning as AiOutlineShieldAlert,
  AiOutlineCheckCircle,
  AiOutlineCloseCircle as AiOutlineXCircle,
  AiOutlineKey,
  AiOutlineReload as AiOutlineRefreshCw,
  AiOutlineWarning as AiOutlineAlertTriangle,
  AiOutlineClockCircle as AiOutlineClock,
  AiOutlineSetting as AiOutlineSettings,
  AiOutlineSun,
  AiOutlineMoon,
  AiOutlineMore as AiOutlineMoreHorizontal,
  AiOutlineMenuFold as AiOutlinePanelLeft,
  AiOutlineBgColors as AiOutlinePalette,
} from 'react-icons/ai';

export interface IconProps extends React.SVGProps<SVGSVGElement> {
  size?: number;
}

export const Icons = {
  mousePointer: AiOutlineMousePointer,
  penLine: AiOutlinePenLine,
  eraser: AiOutlineEraser,
  grid: AiOutlineGrid,
  home: AiOutlineHome,
  pencil: AiOutlinePencil,
  square: AiOutlineSquare,
  hand: AiOutlineHand,
  eye: AiOutlineEye,
  send: AiOutlineSend,
  plusCircle: AiOutlinePlusCircle,
  logIn: AiOutlineLogIn,
  arrowLeftRight: AiOutlineArrowRightLeft,
  shield: AiOutlineShield,
  loader: AiOutlineLoader,
  shieldAlert: AiOutlineShieldAlert,
  checkCircle: AiOutlineCheckCircle,
  xCircle: AiOutlineXCircle,
  key: AiOutlineKey,
  refresh: AiOutlineRefreshCw,
  alertTriangle: AiOutlineAlertTriangle,
  clock: AiOutlineClock,
  settings: AiOutlineSettings,
  sun: AiOutlineSun,
  moon: AiOutlineMoon,
  moreHorizontal: AiOutlineMoreHorizontal,
  search: AiOutlineSearch,
  panelLeft: AiOutlinePanelLeft,
  palette: AiOutlinePalette,
  plus: AiOutlinePlusCircle,
  minus: AiOutlineMinus,
};
