// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovoljdbtmdcxlhrvnaul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92b2xqZGJ0bWRjeGxocnZuYXVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MDMxMjksImV4cCI6MjA1ODQ3OTEyOX0.-ggpCyY0F2zR2MtDN6RaThlZosUc9nr4jL-7tkvSNgs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);