
name: Accessibility Testing

on:
  pull_request:
    branches: [main, master, develop]
  push:
    branches: [main, master, develop]

jobs:
  a11y-tests:
    name: Accessibility Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run component accessibility tests
        run: npm test -- --run "accessibility"
        
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      
      - name: Run E2E accessibility tests
        run: npx playwright test src/tests/e2e/accessibility/
        
      - name: Check for accessibility violations
        if: always()
        run: |
          VIOLATION_COUNT=$(grep -r "violations" playwright-report/ | wc -l)
          if [ $VIOLATION_COUNT -gt 0 ]; then
            echo "::error::Found $VIOLATION_COUNT accessibility violations"
            exit 1
          fi
          
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: accessibility-test-results
          path: |
            playwright-report/
            test-results/
          retention-days: 30

  lighthouse:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build app
        run: npm run build
      
      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
