
name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run lint:ci
      - run: npm run type-check:strict
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run test:coverage
      - name: Update coverage badges
        run: node scripts/update-badges.js
      - name: Commit badge updates
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "docs: update coverage badges [skip ci]" || echo "No changes to commit"
          git push
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      
      # Check bundle size
      - name: Analyze bundle size
        run: |
          npx vite build --config vite.budget.config.js
          
      # Check if any bundles exceed size limits
      - name: Check bundle size limits
        run: |
          node scripts/check-bundle-size.js
  
  e2e-tests:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      
      # Install Playwright browsers
      - name: Install Playwright and browsers
        run: |
          npx playwright install --with-deps
          npm install axe-playwright@^2.1.0
      
      # Run smoke tests first
      - name: Run smoke tests
        run: npm run test:e2e -- tests/e2e/smoke.test.ts
      
      # Run accessibility tests
      - name: Run accessibility checks
        run: npm run test:e2e -- tests/e2e/accessibility/
        
      # Run remaining E2E tests
      - name: Run full E2E test suite
        run: npm run test:e2e -- --grep-invert "smoke|accessibility"
      
      # Run performance tests
      - name: Run performance tests
        run: npm run test:performance
      
      # Performance thresholds
      - name: Check performance thresholds
        run: |
          node scripts/check-performance-results.js
      
      # Enforce accessibility standards
      - name: Verify accessibility compliance
        run: |
          if grep -q "critical" playwright-report/accessibility-violations.json; then
            echo "Critical accessibility violations found"
            exit 1
          fi
      
      # Check coverage threshold
      - name: Check E2E coverage
        run: |
          COVERAGE=$(npx nyc report --reporter=text-summary | grep Statements | awk '{print $3}' | sed 's/%//')
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "E2E test coverage ($COVERAGE%) is below 80%"
            exit 1
          fi
      
      # Upload test results
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
            playwright-report/accessibility-violations.json
          retention-days: 30

  # Security scan job (enhanced)
  security:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      
      # Run npm audit with fail on high or critical issues
      - name: Run npm security audit
        run: |
          echo "Running npm audit..."
          npm audit --audit-level=high
          if [ $? -ne 0 ]; then
            echo "::error::High or critical security vulnerabilities found. Please resolve these issues."
            exit 1
          fi
      
      # Run OWASP Dependency Check
      - name: Run OWASP dependency check
        uses: dependency-check/Dependency-Check_Action@main
        id: dependency-check
        with:
          project: 'canvas-app'
          path: '.'
          format: 'HTML'
          out: 'reports'
          args: >
            --failOnCVSS 7
            --enableRetired
      
      # Upload OWASP dependency check report
      - name: Upload dependency check report
        uses: actions/upload-artifact@v1
        with:
          name: dependency-check-report
          path: ${{ github.workspace }}/reports
      
      # Set up and run CodeQL analysis
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript, typescript
          
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:javascript,typescript"
          
      - name: Check for critical CodeQL alerts
        run: |
          ALERTS=$(gh api graphql -f query='
            query {
              repository(owner: "${{ github.repository_owner }}", name: "${{ github.event.repository.name }}") {
                vulnerabilityAlerts(first: 100) {
                  nodes {
                    securityVulnerability {
                      severity
                    }
                  }
                }
              }
            }' | jq '.data.repository.vulnerabilityAlerts.nodes[] | select(.securityVulnerability.severity == "CRITICAL")')
          
          if [ -n "$ALERTS" ]; then
            echo "::error::Critical security vulnerabilities found. Please resolve these issues."
            exit 1
          fi
